### ISSUE TITLE
Option to show bell icon in top bar, and user-specific notifications

### ISSUE THREAD

**Issue by binaryfire** [pestopancake/laravel-backpack-database-notifications#12]
Hi there

Great package! I'd love to see a couple of features added:

1. The option to show a notifications bell icon on the top right with an ajax dropdown
2. The option to show user-specific notifications

What do you think?

**Comment by pestopancake** [comment]
Good ideas! May well add them but there is no plan to for now, PRs welcome

**Comment by pestopancake** [comment]
Good ideas! May well add them but there is no plan to for now, PRs welcome
