### ISSUE TITLE
Support latest backpack crud, please

### ISSUE THREAD

**Issue by kasperbjerby** [pestopancake/laravel-backpack-database-notifications#16]
Why? Just why?

Locked to 4.0.*|4.1.*|5.0.*

That means it wont work with the latest backpack crud, without manually installing it

Please change it to

"^4.0|^5.0"

**Comment by pestopancake** [comment]
hey @kasperbjerby, good point. I've just prepared a new release (1.0.8-alpha), would be great if you can try it out for us

**Comment by kasperbjerby** [comment]
Works fine, but you should maybe mark this addon as a pro addon, cause you can't use it without backpack pro, cause it uses filters

**Comment by kasperbjerby** [comment]
You also don't seem to support overwriting controllers, models, routes etc.
So i just ended up copying the files, and removing it again

**Comment by pestopancake** [comment]
> Works fine, but you should maybe mark this addon as a pro addon, cause you can't use it without backpack pro, cause it uses filters, so guess i have to modify it myself

paging the boss, @tabacitu. Would be nice if this addon could work within both the free and pro version?

**Comment by kasperbjerby** [comment]
Also a side note, I have modified my own installation to use laravels broadcasting instead of constantly pooling the server for updates, I would also add support for that if I where you

**Comment by pestopancake** [comment]
> Also a side note, I have modified my own installation to use laravels broadcasting instead of constantly pooling the server for updates, I would also add support for that if I where you

Ah yes I've done the same too, but for this package I thought it best not to require broadcasting as not everyone will have that set up on their project.
PRs welcome if you'd like to help add this functionality in - maybe we can allow choosing between polling or broadcasting in the config.
