### ISSUE TITLE
Laravel Backpack V6 Compactibility

### ISSUE THREAD

**Issue by edrisaturay** [pestopancake/laravel-backpack-database-notifications#21]
Hi Guys.. thanks for this great package. 

  Problem 1
    - pestopancake/laravel-backpack-database-notifications 1.0.0 requires backpack/crud 4.0.* -> found backpack/crud[4.0.0, ..., 4.0.63] but it conflicts with your root composer.json require (^6.0).      
    - pestopancake/laravel-backpack-database-notifications[1.0.1, ..., 1.0.5] require backpack/crud 4.0.*|4.1.* -> found backpack/crud[4.0.0, ..., 4.1.71] but it conflicts with your root composer.json req
uire (^6.0).
    - pestopancake/laravel-backpack-database-notifications[1.0.6, ..., 1.0.7] require backpack/crud 4.0.*|4.1.*|5.0.* -> found backpack/crud[4.0.0, ..., 4.1.71, 5.0.0, ..., 5.0.21] but it conflicts with y
our root composer.json require (^6.0).
    - pestopancake/laravel-backpack-database-notifications 1.0.8 requires backpack/crud ^5.0 -> found backpack/crud[5.0.0, ..., 5.6.1] but it conflicts with your root composer.json require (^6.0).        
    - Root composer.json requires pestopancake/laravel-backpack-database-notifications ^1.0 -> satisfiable by pestopancake/laravel-backpack-database-notifications[1.0.0, ..., 1.0.8].

**Comment by ioanandrei** [comment]
Any updates on this? :D

**Comment by ivictor777** [comment]
I’m also interested in whether there will be support for Laravel Backpack 6

**Comment by pestopancake** [comment]
@swayoleg I noticed @laszlo-dashrocks has made some updates for backpack 8 support so I've merged them and prepared a [new release](https://github.com/pestopancake/laravel-backpack-database-notifications/releases/tag/1.0.9-alpha). Would you mind giving this a go?:

`composer require pestopancake/laravel-backpack-database-notifications:1.0.9-alpha`
